[package]
name = "mano-tui"
version = "0.1.0"
edition = "2024"

[[bin]]
name = "mano-tui"
path = "src/main.rs"

[dependencies]
mano-lib = { workspace = true }
ratatui = { workspace = true }
crossterm = { workspace = true }
anyhow = { workspace = true }
clap = { workspace = true }