[package]
name = "mano-cli"
version = "0.1.0"
edition = "2024"

[[bin]]
name = "mano-cli"
path = "src/main.rs"

[dependencies]
mano-lib = { workspace = true }
clap = { workspace = true }
anyhow = { workspace = true }